# https://github.com/shogo82148/actions-setup-perl

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      NO_NETWORK_TESTING: 1
      PERL_MM_USE_DEFAULT: 1
      AUTOMATED_TESTING: 1
    strategy:
      matrix:
        os: ['windows-latest', 'macos-latest', 'ubuntu-latest']
        perl: [ '5.30', '5.28' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn File::Spec ExtUtils::MakeMaker LWP::Simple
          cpanm -iqn Locale::Country Test::Pod::Spelling::CommonMistakes FCGI::Buffer Log::WarnDie B::Lint warnings::unused
          cpanm -i -v --installdeps --notest .
      - name: Run Tests
        run: |
          prove -l t
          perl -MO=Lint ./createdatabase.PL
          perl -c -Mwarnings::unused ./createdatabase.PL
