---
# See https://github.com/actions/virtual-environments

name: Test Code on OS/X
permissions:
  contents: read
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
        perl: ['5.38', '5.36', '5.34', '5.32', '5.30', '5.28', '5.22']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: codecov/codecov-action@v5
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn --skip-satisfied File::Spec ExtUtils::MakeMaker Devel::Cover::Report::Codecov Test::Harness
          cpanm -iqf --skip-satisfied LWP::Simple::WithCache
          cpanm -iqn --skip-satisfied Test::Pod::Spelling::CommonMistakes
          cpanm -iqn --skip-satisfied Test::Portability::Files Test::Carp
          cpanm -iqn --skip-satisfied Test::Pod::Coverage XML::LibXML::Reader Log::Any::Adapter::Log4perl
          cpanm -ifn CGI::IDS
          cpanm -ivn --skip-satisfied --installdeps --notest .
      - name: Run Tests
        run: |
          cover -test
          cover -report codecov
          curl -Os https://uploader.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }}
        shell: bash
        env:
          AUTHOR_TESTING: 1
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          AUTOMATED_TESTING: 1
