---
# See https://github.com/actions/virtual-environments
# https://github.com/marketplace/actions/setup-perl-environment

name: Test Code
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '22 23 6 * *'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        perl: ['5.40', '5.38', '5.36', '5.34', '5.32', '5.30', '5.28', '5.22']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Install Ubuntu Packages
        run: sudo apt-get install libdb-dev
        if: matrix.os == 'ubuntu-latest'
      - run: perl -V
      - name: Install Dependencies
        env:
          AUTOMATED_TESTING: 1
        run: |
          cpanm -iqn ExtUtils::MakeMaker Test::Most Test::Needs Clone
          cpanm -iqnf --skip-satisfied LWP::Simple::WithCache CGI::IDS
          cpanm -iv DB_File
          cpanm -iqn --skip-satisfied HTML::Entities LWP::Protocol::https Log::Any::Adapter::Log4perl Template::Filters Template::Plugin::EnvHash HTML::SocialMedia
          cpanm -ivn --installdeps .
      - name: Make Module
        env:
          AUTHOR_TESTING: 1
          AUTOMATED_TESTING: 1
          NO_NETWORK_TESTING: 1
          NONINTERACTIVE_TESTING: 1
        run: |
          # find . -name build.log | xargs cat
          perl Makefile.PL
          make
      - name: Run Tests
        env:
          AUTHOR_TESTING: 1
          AUTOMATED_TESTING: 1
          NO_NETWORK_TESTING: 1
          NONINTERACTIVE_TESTING: 1
          # CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: prove -l -b t
        # run: |
        #   cover -test
        #   cover -report codecov
        #   curl -Os https://uploader.codecov.io/latest/macos/codecov
        #   chmod +x codecov
        #   ./codecov -t ${{ secrets.CODECOV_TOKEN }}
