---
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-18.04
          - ubuntu-20.04
          - windows-2019
          - windows-2016
        perl: ['5.34', '5.32', '5.30', '5.28', '5.22']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn --skip-satisfied File::Spec ExtUtils::MakeMaker
          cpanm -iqf --skip-satisfied LWP::Simple::WithCache
          cpanm -iqn --skip-satisfied Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Carp Test::Pod::Coverage
          cpanm -iqn --skip-satisfied --installdeps --notest .
      - name: Run Tests
        run: prove -l -b t
        env:
          AUTHOR_TESTING: 1
